name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

  env:
      DB_DATABASE: demo
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_PORT: 3306
      DB_HOST: localhost
      
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute check coding convetion via PHP Code Sniffer
        run: ./vendor/bin/phpcs
    - name: Clear Config
        run: php artisan config:clear
    - name: Run Migration
        run: php artisan migrate -v
    - name: Run Seeder
        run: php artisan db:seed 
    - name: Test with phpunit
        run: vendor/bin/phpunit
      env:
          DB_PORT: ${{ env.DB_PORT }}

